# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Docs

on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinxcontrib-googleanalytics sphinx-rtd-theme
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
